os:
  - linux

language: python

python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - nightly
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install mypy
  - pip install python-coveralls

script:
  - flake8 .
  - mypy .
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
